apiVersion: v1
kind: Service
metadata:
  name: mcp-server-duckdb-private
spec:
  selector:
    app: duckdb-mcp-private
  ports:
    - protocol: TCP
      port: 8000        # The Service listens here
      targetPort: 8000  # The Pod listens here
